pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package -Denforcer.skip=true'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test -Denforcer.skip=true'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }        
    }
}
